### ISSUE TITLE
Support for belongsTo fields

### ISSUE THREAD

**Issue by BenySLO** [whitecube/nova-flexible-content#11]
Adding "belongsTo" field into the "addLayout" triggers error "Call to a member function xy() on array"
In the documentation it is written than all Laravel Nova fields are supported. 

We tried adding BelongsTo fields like this:
`Flexible::make('flex_data')->addLayout('Simple content section', 'test', [BelongsTo::make('xy'),]),`

**Comment by Nyratas** [comment]
Hi @BenySLO,

Relationship fields are quite different than most of the existing "content" fields out there. That's also why they are treated separately from all the other fields in the [official Nova Documentation](https://nova.laravel.com/docs/2.0/resources/relationships.html).

The requested "fields" need existing relationships on the underlying models, but since the fields inside a Flexible Field refer to a "Field group" instead of the resource, this relationship does not exist.

It is however possible to create a custom `BelongsTo` behavior using [Layout Classes](https://whitecube.github.io/nova-flexible-content/#/?id=custom-layout-classes). A more explicit example is provided as a response to #5.

**Comment by codeurient** [comment]
> 
> 
> Adding "belongsTo" field into the "addLayout" triggers error "Call to a member function xy() on array"
> In the documentation it is written than all Laravel Nova fields are supported.
> 
> We tried adding BelongsTo fields like this:
> `Flexible::make('flex_data')->addLayout('Simple content section', 'test', [BelongsTo::make('xy'),]),`

Can you help me please ? I want too to use belongsTo inside flexible but how I do not know.... 

I also can give you remote connection
