### ISSUE TITLE
Emit an Event/Register a watcher on specific field

### ISSUE THREAD

**Issue by kropcik** [whitecube/nova-flexible-content#117]
Hello,

First of all, thanks for this wonderful package and your time. It helps a lot !

Is there a feature to somehow emit an event when specific field is changing/filled or register a watcher from other component to watch for flexible-content field changes ?

**Comment by Nyratas** [comment]
Hi @kropcik,

Thanks for the kind words, sorry for the delay!

I'm not sure to understand your question, do you mean on the field's front-end (a JS event) or in the back-end (a Laravel event) ? Either way, I don't think Nova has specific field-related events that are emitted. However, if you're talking about Laravel events, you could use the model's default eloquent events (for instance the model's [saving](https://laravel.com/docs/6.x/eloquent#events) event) in order to check if the flexible field has changed, then emit your own [event](https://laravel.com/docs/6.x/events).

Hope this helps. I'm closing this issue since it does not seem to be directly related to the package. If I'm wrong, do not hesitate to open it again.

Have a great day!
