### ISSUE TITLE
Some questions about storing in the json column or seperate table.

### ISSUE THREAD

**Issue by ziming** [whitecube/nova-flexible-content#133]
Hi there,

Thanks for this excellent package. I am trying to learn and I encountered some difficulties.

My questions are below:

1. Given this method, where do I specify which json column to use on the table to store the json array?

```php
public function fields(Request $request)
{
    return [
        // ...

        Flexible::make('Content')
            ->addLayout('Simple content section', 'main-content', [
                Text::make('Title'),
                Markdown::make('Content')
            ])
            ->addLayout('Video section', 'awesome_videos', [
                Text::make('Title'),
                Image::make('Video Thumbnail', 'thumbnail'),
                Text::make('Video ID (YouTube)', 'video'),
                Text::make('Video Caption', 'caption')
            ])
    ];
}

```

2. If I want store in proper tables, I see in the docs it shows this example:

```php
/**
 * get the field's value
 *
 * @param  mixed  $resource
 * @param  string $attribute
 * @param  Whitecube\NovaFlexibleContent\Layouts\Collection $layouts
 * @return Illuminate\Support\Collection
 */
public function get($resource, $attribute, $layouts) {
    $blocks = $resource->blocks()->orderBy('order')->get();

    return $blocks->map(function($block) use ($layouts) {
        $layout = $layouts->find($block->name);

        if(!$layout) return;

        return $layout->duplicateAndHydrate($block->id, ['value' => $block->value]);
    })->filter();
}

/**
 * Set the field's value
 *
 * @param  mixed  $model
 * @param  string $attribute
 * @param  Illuminate\Support\Collection $groups
 * @return void
 */
public function set($model, $attribute, $groups)
{
    $class = get_class($model);

    $class::saved(function ($model) use ($groups) {
        $blocks = $groups->map(function($group, $index) {
            return [
                'name' => $group->name(),
                'value' => json_encode($group->getAttributes()),
                'order' => $index
            ];
        });

        // This is a quick & dirty example, syncing the models is probably a better idea.
        $model->blocks()->delete();
        $model->blocks()->createMany($blocks);
    });
}
```

Is blocks() a relationship method? Like it can be books() or something else?

Also I see name and order, what are they for? My assumption is by default the values are stored in a json array like this. Although I can't be sure as when I try to save, it just say success and nothing changed on my table.

```php
[
    ['first_name' => 'John', 'last_name' => 'Doe'],
]

```

Thank you.

**Comment by scaventum** [comment]
You can use `table_column->json_column` accessor to store the value in a json format. e.g:
```
Flexible::make('Content','content->header_content')
            ->addLayout('Simple content section', 'main-content', [
                Text::make('Title'),
                Markdown::make('Content')
            ])
            ->addLayout('Video section', 'awesome_videos', [
                Text::make('Title'),
                Image::make('Video Thumbnail', 'thumbnail'),
                Text::make('Video ID (YouTube)', 'video'),
                Text::make('Video Caption', 'caption')
            ])
```


dont forget to cast column as array in model

**Comment by ziming** [comment]
Okay so for awesome_videos

Does this mean for the following:

```php
->addLayout('Video section', 'awesome_videos', [
                Text::make('Title'),
                Image::make('Video Thumbnail', 'thumbnail'),
                Text::make('Video ID (YouTube)', 'video'),
                Text::make('Video Caption', 'caption')
            ])
```

It will be stored in the 'awesome_videos' json column in the table as an array?

Look forward to my question on the proper tables too if possible. Thank you

**Comment by Nyratas** [comment]
No, it won't. I'll try to give a complete answer.

> 1. Given this method, where do I specify which json column to use on the table to store the json array?
> 
> ```
> public function fields(Request $request)
> {
>     return [
>         // ...
> 
>         Flexible::make('Content')
>             ->addLayout('Simple content section', 'main-content', [
>                 Text::make('Title'),
>                 Markdown::make('Content')
>             ])
>             ->addLayout('Video section', 'awesome_videos', [
>                 Text::make('Title'),
>                 Image::make('Video Thumbnail', 'thumbnail'),
>                 Text::make('Video ID (YouTube)', 'video'),
>                 Text::make('Video Caption', 'caption')
>             ])
>     ];
> }
> ```

As any other field out there, the Flexible field's `make()` method accepts two arguments: first the displayed label, then the field's name. If the field's name is not provided, Laravel will try to transform the label into a valid name. This "name" attribute is also the default column name on the model where the field's value will be stored. In other words, in the example above, Nova will try to store the Flexible's value in a column called `content`.

As @scaventum pointed out, if you want to store the value in a JSON object ( = nesting it in a JSON object), you can use the arrow notation (`column_name->json_attribute`) but I have to admit I don't see why it would be useful in this situation.

> Is blocks() a relationship method? Like it can be books() or something else?

Yes, it is.

> Also I see name and order, what are they for?

Let's take in consideration the following example. Using Nova's UI, you want to add the following content to your Flexible field :

```
1. awesome_videos
2. main-content
3. awesome_videos
```

The `name` attribute is the identifier of the layout that was used. In this case, it will be "awesome_videos" for the first group, then "main-content", then "awesome_videos" again. We store this information in the table in order to know which layout was used, which could be useful if you want to render it using a specific blade template on your website for example.

The `order` attribute is the index in which the layout has been used, in other words : "1", "2", "3". This is useful since it helps keep track of the user-defined group ordering, which you could retrieve using a simple `->orderBy('order')` call on your eloquent model.

> My assumption is by default the values are stored in a json array like this. Although I can't be sure as when I try to save, it just say success and nothing changed on my table.
> 
> ```
> [
>     ['first_name' => 'John', 'last_name' => 'Doe'],
> ]
> ```

The `json_encode($group->getAttributes())` will indeed return a similar structure. However, this is not the field's default behavior, this is what happens when you use the custom resolver you showed in your post.

Hope this helps.
