### ISSUE TITLE
problem wtih parsing in strpos().

### ISSUE THREAD

**Issue by BenySLO** [whitecube/nova-flexible-content#16]
Because i used indexing with integer and it didn't work I'm posting this just in case you think its a bug i had the following error : 

> strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior

And had to change **whitecube/nova-flexible-content/src/Http/ScopedRequest.php**
Around line 130 from:
`$analysis['raw'] = substr($attribute, strpos($attribute, $key) + strlen($key . '__'));`
To:
`$analysis['raw'] = substr($attribute, strpos($attribute, strval($key)) + strlen($key . '__'));`
Might add I use PHP version 7.3.3 but on my other machine with PHP 7.2.* it worked without the fix.

**Comment by Nyratas** [comment]
Hi @BenySLO,

Sorry for my late response, I've been quite busy these days. Thank you for sharing this issue! 

Just for the sake curiosity, could you show how you're getting integer keys? Are you using integers as field names?

Indeed, using `strpos` with non-string needle has been [deprecated in PHP 7.3](https://www.php.net/manual/en/function.strpos.php). Your fix could in my opinion be merged into the package, but first I want to be certain to fully understand why and how you're having an integer instead of string key here.

**Comment by voidgraphics** [comment]
This is included in the new [v0.1.3](https://github.com/whitecube/nova-flexible-content/releases/tag/v0.1.3) release.

**Comment by BenySLO** [comment]
@Nyratas must have missed your notification, sorry for not responding. Since I'm here, I'm not sure how i got integer keys, but it was probably because I've created my own resolver for my preset, which I've probably somehow managed to insert integer keys as field name.
