### ISSUE TITLE
hasFlexible::flexible() returns original value instead of Colleciton

### ISSUE THREAD

**Issue by tobz-nz** [whitecube/nova-flexible-content#169]
HasFlexible trait line 23

```php
        if(app()->getProvider(NovaServiceProvider::class)) {
            return $flexible;
        }
```

seems to always be true and so returns the original value instead of converting to a Layout Collection.

**Comment by Nyratas** [comment]
Hi @tobz-nz,

Thanks for reporting this, will take a look at it as soon as possible.

**Comment by voidgraphics** [comment]
Hi @tobz-nz, I can't seem to reproduce this problem. It does not return true when outside of Nova, and I do get the collection. It must be something specific in your application that loads the NovaServiceProvider when it's not supposed to.

If you find the cause please report back! Thanks.

**Comment by SquareBeard** [comment]
Cast looked elegant but if we can't use it inside Nova I'll have to stick with the old way.
FYI, it is needed inside Nova for stuffs like Scout synchronisation but I guess there is other use cases.

Maybe there is less restrictive way to do this.

**Comment by voidgraphics** [comment]
Did I misunderstand the issue? If so, sorry!
Is the problem that you want to get a collection back within nova? I am not too familiar with Scout. Can you enlighten me?

**Comment by SquareBeard** [comment]
I don't know about the original issue. But for me that's exactly the problem yes.

As for Scout, every time you create or update a resource, a `toSearchableArray` method is called on the model to format the data before it is sent to a full-text search service like Algolia.
To format the data I need the parsed flexible content, but it's not working with cast because we are  in Nova.

**Comment by tobz-nz** [comment]
Yes I need to get the collection within Nova - I am dynamically building up a flexible field based on the flexible fields of another related model.

So far my work around has been `$model->toFlexible($model->someAttribute)`.
Its a little naff, but it works.

I've also noticed that I need to do the same thing when not using Nova as well (within the same codebase though).

I am loading the `NovaServiceProvider` as per default in `config/app.php` - which is always loaded on every request regardless of if the request is to a Nova endpoint or not.

**Comment by voidgraphics** [comment]
@SquareBeard thanks for the clarification, as I mentioned in my edit, you can use the `toFlexible` method to convert the raw value to a layout collection. If you have another bug unrelated to this, feel free to open an issue for it! (unless you already have, I am slowly working my way through)

@tobz-nz We haven't really considered the fact you could want to load the layout collection while within Nova, which is why it is currently designed this way. We're open to changing that, but as it is out of the scope of our needs, we would ask you to submit a PR with a change that fits those needs. As you said though, the `toFlexible` method already does what you need.

Also, there seems to be some confusion: there are two `NovaServiceProvider` classes. One that gets loaded on every request, as configured in `config/app.php`, and one that only gets loaded on Nova endpoints, which is the one we are referencing in that if statement you mentioned in your original comment. They have different namespaces: `App\Providers\NovaServiceProvider` vs `Laravel\Nova\NovaServiceProvider`. So it should mean that outside of Nova endpoints, you should not need to use the `toFlexible` method, because the `flexible` method already returns the layout collection.

I hope that clarifies it a bit!

**Comment by tobz-nz** [comment]
Ah, I missed the different Namespace there - my bad.
I think my use case is pretty edge so probably don't worry about it.

I do have the issue even in `Tinker`, migrations and tests as well as normal app HTTP requests.

**Comment by tobz-nz** [comment]
An example from tinker:

```
dump(app()->getProvider(NovaServiceProvider::class));
$op = App\TuningOption::find(30);
dd($op->fields);
``

outputs
```
null
"[{"key": "pac3adc23659db76j", "layout": "select", "attributes": {"options": [{"key": "pwe3adg73656db76j", "layout": "option", "attributes": {"label": "Economy", "price": 380}}, {"key": "phe3adc27559db76f", "layout": "option", "attributes": {"label": "Towing", "price": 380}}, {"key": "pcg3adc336569b76d", "layout": "option", "attributes": {"label": "Power", "price": 380}}], "required": false}}]"
```

This is using the new custom Cast. Same output is using `$op->flexible('fields')`

**Comment by tobz-nz** [comment]
Ah crap - I just realised I wasn't importing the NovaServiceProvider whisch is why its null.
Importing it correct and it is loaded.

... now to figure out why its loaded.

**Comment by voidgraphics** [comment]
And you're importing `Laravel\Nova\NovaServiceProvider`, not  `App\Providers\NovaServiceProvider`, correct?

The code responsible for loading the provider on Nova endpoints is in the `Laravel\Nova\Http\Middleware\ServeNova` class. 

It's fairly simple code though and the only thing I could see being the culprit is if you changed your nova path in the config to something that would load it on every page.

What do you have in `config/nova` under the `path` key?

**Comment by tobz-nz** [comment]
yes I'm loading the correct Service Provider.
Nova path is the default `/nova`.

**Comment by tobz-nz** [comment]
I've done a search through my codebase and the wrong serviceProvider is not mentioned anywhere.

**Comment by voidgraphics** [comment]
Can you do a `dd($this->isNovaRequest($request))` at the beginning of the `handle` method in the `ServeNova` class?

**Comment by tobz-nz** [comment]
Its `false`

I just did some more testing.
In an app controller, its actually working correctly. Not sure if this is a new thing or I just got it wrong and it was only Nova controlers.

Tinker still returns the raw array instead of the layout collection though - and does not dd() in the middleware.

**Comment by tobz-nz** [comment]
... adding `|| !app()->runningInConsole()` of the check in `HasFlexible.php` line 35 fixes the Tinker problem.

**Comment by gwleuverink** [comment]
@voidgraphics I'm having a similar issue.

**How to reproduce**
I need to test some models with flexible content. I have a factory that fills that column with some default value.

When I run the test, the `cast` method inside the `HasFlexible` trait just returns the string. When I use the same data on my frontend site it is correctly casted to a layout collection.

You can reproduce it easily by using a model with a flexible column in a test.

**What I'd expect**
I'd expect the value to be casted to a layout collection in both cases.

**Why this happens**
The reason this happens is that the `cast` method uses this check to see if it needs to cast the value or just return the json string:

``` php
if (app()->getProvider(NovaServiceProvider::class) {
    //
}
```

The problem is that when I run my test this check always passes.. The NovaServiceProvider is always registered when running in the console. The reason is the following part in NovaCoreServiceProvider. :
``` php
public function boot()
{
    if ($this->app->runningInConsole()) {
        $this->app->register(NovaServiceProvider::class);
    }
    //

```

**Possible solution**
I fixed it by providing my own `HasFlexible` trait.

``` php
namespace App\Concerns;

use Whitecube\NovaFlexibleContent\Concerns;

trait HasFlexible
{
    use Concerns\HasFlexible;
    
    /** @inheritDoc */
    public function cast($value, $layoutMapping = [])
    {
        if (app()->getProvider(NovaServiceProvider::class) || ! app()->environment('testing')) {
            return $value;
        }

        return $this->toFlexible($value ?: null, $layoutMapping);
    }
}
```

This solution works well, but it is a pain to have to do this in every project where I have to test some model with flexible content. 

This issue still persists. I believe testing should be a first class citizen really. @voidgraphics would you be open to reopening this issue?

**Comment by voidgraphics** [comment]
Hi @gwleuverink your solution looks good to me and I would accept it if you were to submit a PR for it.

**Comment by gwleuverink** [comment]
That is great! I'm not sure if this would fix @tobz-nz original issue though. Do you want me to create a new issue specifically for testing before submitting a PR?

**Comment by voidgraphics** [comment]
No need, just the PR will do! Thanks
