### ISSUE TITLE
why you don't merge pull requests ????

### ISSUE THREAD

**Issue by zareismail** [whitecube/nova-flexible-content#172]
why you don't merge pull requests ???

**Comment by voidgraphics** [comment]
Hello @zareismail!

First, thank you for opening that PR. Your help is much appreciated. Sorry we couldn’t get to it quicker - but I hope you can understand that we provide this for free and as such, it is sometimes difficult to allocate time for maintenance. @Nyratas and I are part of a company with numerous other employees, and companies need to make money to survive. We do a lot of client work, and that takes a lot of our time currently, so there’s little left for open source.

We do plan on getting better though! We are all very committed to open source and would love to make it a bigger part of our daily work. We are currently working on ways to make that happen - but to tell you the truth, in order to do so, we are sacrificing our energy and our money.
We have recently opened our [Sponsorship page](https://github.com/sponsors/whitecube) in hopes to get some help on that front - if your business depends on it, helping us out will allow us to allocate more time on maintenance and get to your issues and PRs quicker.
It is not mandatory, and we hope to get to all issues eventually regardless of our sponsorships, but it would for sure allow us to do it quicker.

Thanks for caring :+1:
