### ISSUE TITLE
Feature request : Using nova-page with nova-flexible-content

### ISSUE THREAD

**Issue by wimurk** [whitecube/nova-flexible-content#19]
I am using this package with the whitecube/nova-page. It would be very nice to combine these two. If this is already done, please provide some docs. 

For example i have flexible content named Slider.
Inside the view i can do `Page::get('slider')` this returns the flexible content as a json string. It would be great if i could use something like `Page::flexible('slider')` or `Page::block('slider')`

**Comment by Nyratas** [comment]
Hi @wimurk,

Both packages already work well together. By default models (or templates) do not parse JSON strings. Since each Flexible Content can be used in different ways, we did not add a default way to achieve this, giving you the opportunity to define that behavior on your own.

There are two ways you could do this. The first one is defining a specific mutator on the Template class:

```php

public function getMyFlexibleContentAttribute()
{
      // perform your parsing logic on $this->attributes['name-of-the-flexible-content-attribute']
      return $parsedValue;
}
```

Or you can pass a closure function to `Page::get` as follows: 

```php
Page::get('name-of-the-flexible-content-attribute', function($json) {
      // perform your parsing logic on $this->attributes['name-of-the-flexible-content-attribute']
      return $parsedValue;
});
```

Your suggestion is however interesting too, and could be implemented if you want. You could for example create  a `ParsesFlexibleContentValues` trait and use it on the Template classes exploiting the flexible content. 

This trait could contain the following method:

```php

public function getFlexible($attribute)
{
      // perform your parsing logic on $this->attributes[$attribute]
      return $parsedValue;
}
```

Which would let you use `Page::flexible('slider')` as suggested.

**Comment by wimurk** [comment]
@Nyratas Thanks, the last one was correct. Maybe a good idea to put this int he docs?

**Comment by Nyratas** [comment]
Hi @wimurk glad it helped. We could indeed mention it in the docs. If you have a few minutes, maybe you could share your experience and prepare a draft we could insert in the docs? Don't feel obligated, we'll do it or review it anyway.
