### ISSUE TITLE
Image value is missing when nesting JSON with '64robots/nova-fields'

### ISSUE THREAD

**Issue by xenonthong** [whitecube/nova-flexible-content#20]
When I try to use flexible-content with 64robots/nova-fields's json field, the image value gets removed.

## Use case:
I have other non-repeatable fields that need to have its value stored together in the json column in my database. Since flexible-content only saves its own data in the json column, in order to overcome this behaviour, I've included 64robots/nova-fields' json field, so that I can save other data together with flexible-content's data.

```php
<?php

use Laravel\Nova\Fields\Heading;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Fields\Image;
use R64\NovaFields\JSON;

public function fields(Request $request)
{
    return [
        Heading::make('Hero'),

        // Stores it as 'title' under 'content' json column.
        Json::make('', [Text::make('title')], 'content'),

        Heading::make('Gallery Images'),
        
        // Stores it as 'gallery_images' under 'content' json column.
        Json::make('', [
            Flexible::make('Gallery Images')
                    ->addLayout('Gallery section', 'gallery', [
                        Text::make('Title'),
                        Image::make('Video Thumbnail', 'thumbnail'),
                    ]),
        ], 'content'),
    ];
}
```

I'm currently using `"whitecube/nova-flexible-content": "^0.1.4"`

**Comment by Nyratas** [comment]
Hi @xenonthong,

Three things :
- Having two fields saving data to the same attribute seems like you're looking for problems. I guess this _should_ work as intended with R64's Json field, but why not define the flexible content _inside_ the JSON field? Also, it seems to me you should probably save to different attributes since "Hero" and "Gallery Images" are two different things.
- In order to save images (or any other files) in a flexible-content, when need to have access to the Request object containing the fields. My guess is that the Request object has been altered by the JSON field and therefore, this could be an issue with R64's package.
- If you want to create a "content-builder" that saves all its data to the same attribute, you should probably only use the flexible field and add the "Hero" & "Gallery Images" as layouts in the flexible field. You can nest flexible fields, meaning your current "Gallery section" layout can be nested inside a potential "Images Gallery" layout.
