### ISSUE TITLE
Thin package for laravel

### ISSUE THREAD

**Issue by ErenPhayte** [whitecube/nova-flexible-content#257]
We have a unique situation. We have 1 Nova CMS that is used for managing various different content types. We have a suite of microservices that are not part of the CMS - they are standalone and lightweight but do connect to the same data sources the CMS is connected to via shared Models. The challenge we have is we use the Flexible content package in Nova but would like to use the helper functions in our Microservice to generate the JSON payload in the format and structure we want it in. The problem we have is the minute we add this package to the API, we have to install Nova package too which we do not want.

Do you perhaps have a separate package that just has the helpers, etc to work with the data only (and doesn't care for Nova so it could be used in other systems)? Or at least is there a view to separate these two concerns. Allowing for the Nova specific package to work as is, but if we need a thin package else where we can just include that subset?

**Comment by Nyratas** [comment]
Hi @ErenPhayte,

We do not have that stand-alone package at the moment, but since we're developing a similar flexible-content field for another Laravel system, I guess it could be possible to extract pure Nova-unrelated logic into another package. I don't know when this will be since we're quite busy on other big projects too.

I definitely like the idea and will keep you posted as soon as we make a move in that direction.
