### ISSUE TITLE
Images in Nested Subfields with Same Type not working.

### ISSUE THREAD

**Issue by jackabox** [whitecube/nova-flexible-content#29]
Nova Version: 2.0.5
Plugin Version: 0.1.6

I have a block of code in my that adds a nested repeatable field. Which looks like the following:

```
->addLayout('Fifty/Fifty Block', 'fifty_split', [
                    Flexible::make('Items')
                        ->addLayout('Image', 'image', [
                            Image::make('Image', 'image')
                        ])
                        ->addLayout('Video', 'video', [
                            Image::make('Cover', 'cover'),
                            Text::make('Video URL', 'video_url')
                        ])
                        ->addLayout('Text', 'text', [
                            Text::make('Heading'),
                            NovaTrumbowyg::make('Body')
                        ])
                ])
```

When I add a new top-level field, it'll create the necessary block and allow for me to fill out the data as intended. I'll fill out several images and content then save, and it'll only save the images for the first "Fifty Fifty Block" and delete the images for the latter while keeping the subfields.

![Screenshot_2019-05-29 FWK(1)](https://user-images.githubusercontent.com/3618433/58553826-d28aac80-820d-11e9-8501-4ba9dea89c67.png)

**Comment by jackabox** [comment]
May possibly be related to #24

**Comment by voidgraphics** [comment]
Thanks for the report, we will check this out friday.

**Comment by Nyratas** [comment]
Closing this issue since it seems to be solved by 603e4a9. @jackabox, could you confirm? Do not hesitate to reopen the issue if needed. Thanks!

**Comment by zeyadaverotech** [comment]
fucker mother why you don't solve it since May 2019 !!

**Comment by toonvandenbos** [comment]
@zeyadaverotech _why you don't_ learn to read? _Why you don't_ try to ask politely? _Why you don't_ try by yourself first? 

I'm curious if you ever had a positive response on a message like this.

Oh, and... I saw what you wrote before you edited your message. We get email notifications, you know? You must be a very frustrated person and I hope you'll get well soon, but in the meantime you should probably try another job because you clearly don't belong here. Bye.
