### ISSUE TITLE
Regression: Delete button is broken

### ISSUE THREAD

**Issue by Senexis** [whitecube/nova-flexible-content#513]
After the Laravel 11 compatibility pull request (#509) the delete button for deleting a block (using `confirmRemove`) has regressed to being broken again.

![image](https://github.com/whitecube/nova-flexible-content/assets/6360733/1add58ea-8db1-4871-a1f3-f3f4ebd38774)

Currently it is not possible to delete the block due to the delete "button" no longer being an actual button.

Relevant `composer show -i` output:
```
laravel/framework                            v11.0.8
laravel/nova                                 4.33.0
whitecube/nova-flexible-content              v1.1.0
```

**Comment by justindantzer** [comment]
@Senexis I could be mistaken, but I believe this issue is related to a reported issue over on the [Nova issue repository](https://github.com/laravel/nova-issues/discussions/6025), and not related to the recent Laravel compatability PR.

Apparently, some components have been removed, and it is likely the `<danger-button/>` component used on the [DeleteGroupModal.vue](https://github.com/whitecube/nova-flexible-content/blob/e28bd3dfc8ae7c5e83f6397128017d327a1465f5/resources/js/components/DeleteGroupModal.vue#L31) needs to be replaced with another component that is available.

If someone is able to throw together a PR, this may be what's required. It looks like within Nova (looking at the `DeleteResourceModal.vue` in the source) there is a button component used similarly to this:
```vue
import { Button } from 'laravel-nova-ui';

<Button
    type="submit"
    :loading="working"
    state="danger"
    label="Delete"
/>
```

**Comment by Jaspur** [comment]
@voidgraphics can you solve this?

**Comment by voidgraphics** [comment]
Yes actually, I have this scheduled for later today!

**Comment by voidgraphics** [comment]
Should work now in `v1.1.1`
