### ISSUE TITLE
Unable to parse incoming Flexible content, data should be an array. 

### ISSUE THREAD

**Issue by thebluebug** [whitecube/nova-flexible-content#55]
v0.1.8 doesn't work when we wrap a Flexible field with R64 Nova Fields' JSON field (https://github.com/64robots/nova-fields/).

Example code:
```
            JSON::make('Details', [
                Flexible::make('Student Choice Selections', config('magento.gp_bundle_student_choices'))
                    ->button('Add Student Choice Item')
                    ->addLayout('Student Choice Selections', 'student_choice_selections', [
                        Text::make('Choice Description', config('magento.gp_bundle_student_products.selection_title'))
                            ->fieldClasses('choice-description-field px-8 py-6')
                            ->rules('required'),
... 
            ], 'data')->fieldClasses('w-full')
                ->labelClasses('w-1/6 px-8 py-6 hidden')
                ->hideFromIndex(),
```

We get this error: 
`localhost.ERROR: Unable to parse incoming Flexible content, data should be an array. {"userId":2,"exception":"[object] (Exception(code: 0): Unable to parse incoming Flexible content, data should be an array. at /var/www/html/vendor/whitecube/nova-flexible-content/src/Flexible.php:268)`

I know it's expecting an array, but we need our data in JSON format. Is there any workaround?

**Comment by Nyratas** [comment]
Hi @thebluebug,

I don't understand why you'd want to wrap a single Flexible field with R64's JSON field. The field provided by this package does already store the data as JSON.

If you want your data to be stored differently (maybe another JSON structure), you could create a [custom resolver](https://whitecube.github.io/nova-flexible-content/#/?id=custom-resolver-classes).

Anyway, I wouldn't wrap the field inside another (useless, in this case) parent field since they do not always provide the correct resolving procedure.

**Comment by thebluebug** [comment]
I took out the other fields for brevity, so it's not just a Flexible field that's wrapped with R64's JSON field. 

Example payload:
```{
	"name": "Test",
	"price": "60",
        ...
	"student_choices": [
		{
			"key": "3aea60dd6514c376",
			"layout": "student_choice_selections",
			"attributes": {
				"title": "Choice",
				...
				"max_allowed": "2"
			}
		}
	],
	...
}```

So it sounds like we need a custom resolver as you said?

**Comment by Nyratas** [comment]
Hi @thebluebug,

Sorry, didn't know you removed the other fields, it all makes more sense now :)

When are you getting the error exactly? When displaying a Flexible field or when submitting a form (create/update request)? If it's only when submitting a form, a resolver won't help, sorry.

What I'm guessing is that R64's fields do not parse their incoming Request input as we do before passing it to the contained fields, which is kinda problematic. I'll have to look further into this but it may be a good idea to open an issue on R64's repository too. Please keep me posted if you do.

An alternative approach could be to use a parent Flexible content instead of the JSON field. Nested flexible fields work fine. You can then remove the "Add layout" button using [the `limit(1)` method](https://whitecube.github.io/nova-flexible-content/#/?id=limiting-layouts). The resulting UI will be slightly different, but maybe more consistent for your users. And again, you can control how the "fake JSON field" will store & retrieve its value by applying a [custom resolver](https://whitecube.github.io/nova-flexible-content/#/?id=custom-resolver-classes) on it. I honestly think this would be a better and certainly quicker approach. Let me know how this  works out!

**Comment by thebluebug** [comment]
> When are you getting the error exactly? When displaying a Flexible field or when submitting a form (create/update request)? If it's only when submitting a form, a resolver won't help, sorry.

I'm getting the error when submitting the form (create and update).

> What I'm guessing is that R64's fields do not parse their incoming Request input as we do before passing it to the contained fields, which is kinda problematic. I'll have to look further into this but it may be a good idea to open an issue on R64's repository too. Please keep me posted if you do.

Okay, will do!

>An alternative approach could be to use a parent Flexible content instead of the JSON field. Nested flexible fields work fine. You can then remove the "Add layout" button using the limit(1) method. The resulting UI will be slightly different, but maybe more consistent for your users. And again, you can control how the "fake JSON field" will store & retrieve its value by applying a custom resolver on it. I honestly think this would be a better and certainly quicker approach. Let me know how this works out!

I tried this approach just now, but the UI isn't going to work out for us (unless I spend a lot of time matching our comp design). As you probably know, Nova fields are so inflexible when it comes to custom styling - so frustrating! The limit must be new (currently we're on v0.1.7 until I can resolve this issue for us), and I was looking for something like that as well unrelated to this current issue. Great addition!
