### ISSUE TITLE
Downdown limits to 3 layouts with CSS

### ISSUE THREAD

**Issue by LorenzoSapora** [whitecube/nova-flexible-content#65]
In `resources/js/components/FormField.vue` we have the line:

```html
<div v-if="isLayoutsDropdownOpen"  class="overflow-hidden absolute rounded-lg shadow-lg max-w-full mb-3 pin-b max-h-search overflow-y-auto border border-40">
```
Which contains `overflow-hidden` and `overflow-y-auto`, which limits the list to the last 3 layouts.

I completely understand not wanting to overflow off the screen, or even over/under UI elements, but this is strangely limiting, and not even scrollable. I'm surprised no one else has hit this issue.

If no one has any issues with just removing the overflow classes, I'll push a PR for this.

**Comment by voidgraphics** [comment]
Strangely I haven’t encountered this even with 5+ layouts, even though admittedly that was a while ago and I can’t recall if we have made changes to this since then. We would definitely accept a PR that fixes it, but we’d like to ask to have it scrollable then. It would indeed be impractical to have the dropdown overflow the page. Thanks!

**Comment by LorenzoSapora** [comment]
There are some improvements that can be made, but aren't fit for that particular PR/this issue.

For example, we could probably drop the dropdown below the button, for further breathing room, or maybe make it a modal window for even more space to play with

**Comment by voidgraphics** [comment]
If I remember correctly we have the dropdown above the button to allow it to have more space in case the flexible field is last on the page. I think a modal could solve that but it is also maybe a little overkill - it would be a drastic context change from a visual standpoint, and it might not be as easy to understand. Also I think it would feel a little heavy, because it would create that context change every time you have to add a layout, which may be a lot of times in a row.

That being said I do agree that the dropdown could be improved upon, it’s far from perfect. Always open to suggestions!

**Comment by LorenzoSapora** [comment]
Oh it would definitely be too heavy for 1 to say 10 layouts, but say for example you were using this for some sort of page builder, an option function like `Flexible::make('Page', 'content')->useModal()` would be nice to have. I don't have the spare time this weekend, but I'll put it on my todo list for next weekend, and I'll revisit this. 

Always happy to help.
