### ISSUE TITLE
How to use Advanced Nova Media Library inside Custom Layout Class

### ISSUE THREAD

**Issue by vayurobins** [whitecube/nova-flexible-content#80]
Hi.
I would like to use this Flies field inside my custom layout class, but I get an error that it can't find getMedia(). getMedia() nees to be implemented on the model, but since there is no model on the layout class, how would I do this? https://packagist.org/packages/ebess/advanced-nova-media-library
Thanks

**Comment by voidgraphics** [comment]
Hello, please refer to #33. It seems we haven't updated the documentation yet to explain this, we'll get it done soon.

**Comment by cgarofalo** [comment]
@voidgraphics Has the documentation been updated yet? #33 is a hot mess.

**Comment by voidgraphics** [comment]
@cgarofalo Sorry, I don't believe it has. I have not had time to get to it. [The relevant explanation in that issue is this one](https://github.com/whitecube/nova-flexible-content/issues/33#issuecomment-523845673).

The PR he mentioned has since been merged into advances-nova-media-library, so make sure that is up to date in your composer dependencies.
