### ISSUE TITLE
flexible() returns string when in Nova

### ISSUE THREAD

**Issue by zippoxer** [whitecube/nova-flexible-content#94]
Due to this check at `HasFlexible`:

```php
public function flexible($attribute, $layoutMapping = [])
    {
        $flexible = $this->attributes[$attribute] ?? null;

        // NOTE: returns true when in Nova
        if(app()->getProvider(NovaServiceProvider::class)) {
            return $flexible;
        }
        
        return $this->toFlexible($flexible ?: null, $layoutMapping);
    }
```
We get the JSON string instead of the `Collection` when in Nova (as opposed to the non-admin front-end).

Is this check necessary or can we safely remove it?

Thanks!

**Comment by Nyratas** [comment]
Hi @zippoxer,

Inside Nova, the package uses its [assigned `resolver` class](https://whitecube.github.io/nova-flexible-content/#/?id=custom-resolver-classes) in order to parse the Flexible field's values. The result will also be a `Collection`. Since one's not required to use the `HasFlexible` trait, it is better to only return the "raw" value from the model before our Nova field starts doing its thing with it.

It should not be removed.

Could you explain why you'd want to remove it? Maybe there's another way to achieve it.

Have a nice day!

**Comment by zippoxer** [comment]
Hi @Nyratas 

I have a use case where I'm calling `flexible()` from inside Nova. Here's what I have right now:

```php
    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            
            Select::make(__('Status'), 'status')
                ->options(function () {
                    $projectOptions = app(ProjectOptions::class);

                    return $projectOptions->toFlexible(
                        $projectOptions->flexible('status_types')
                    )->map(function ($type) {
                        return $type->serial_number . '. ' . $type->status;
                    });
                }),
        ];
    }
```

The issue is that I have to call `toFlexible` in order to get what is expected. Before, I was only calling `flexible()` and it was a pretty hard to debug why it returned a string.

Thanks!

**Comment by Nyratas** [comment]
Hi @zippoxer,

If you take a look at `src/Concerns/HasFlexible` you'll see that you can bypass the Nova restriction by calling `toFlexible` directly instead of `flexible`. You can give it the flexible's raw value (the JSON string probably) directly and it will take care of everything.

I'm guessing `projectOptions` is your model which is implementing the `HasFlexible` trait? If so, Instead of:
```php
return $projectOptions->toFlexible(
    $projectOptions->flexible('status_types')
)->map(...);
```

You should do:
```php
return $projectOptions
    ->toFlexible($projectOptions->status_types)
    ->map(...);
)
```

You basically don't need the `flexible` call if you're using `toFlexible` directly.

I'm closing this issue since it is not one, but feel free to give your feedback.
