### ISSUE TITLE
Ability to use nova-flexible-content to store a single layout

### ISSUE THREAD

**Issue by tpetry** [whitecube/nova-flexible-content#98]
Nova Flexible Content perfectly suits the need to store a number of objects. However, sometimes you don't want to store a large number of objects, but just one. For example, you could try to store a configuration consisting of several attributes in a database column. So you want to store a single JSON object in the database and not a number of JSON objects as an array.

The idea is to store in a database column e.g. the information:
```json
{
  "someattribute": "1",
  "anotherattribute": "yeah",
  "a-third-is-nice": "ok, it's clear now"
}
```

This need is met by the 64robots/nova-fields package, but does not support all field types and has other problems that nova-flexible-content does not have. It would be nice if nova-flexible-content could be extended by a setting to store only one fixed layout. The following adjustments would be necessary:
* the up/down and delete buttons on the left would have to be removed
* No more "Add {Layout}" button when creating resources, the form is displayed by default
* No array of JSON objects will be created anymore but only a JSON object directly.

**Comment by Nyratas** [comment]
Hi @tpetry,

Thanks for your message. We are aware of the issues with `64robots/nova-fields` and I would suggest to open an issue there in order to fix their package instead of trying to find a "dirty" solution for your problem with our package. Nova Flexible Content is meant to be a repeatable field, it would not make much sense if there was an option that would transform it to a simple JSON field.

However, just for your information, it is already possible to achieve your request with the current tools and options provided by this package : 
- You cannot remove the up/down/delete buttons from the UI for the moment, but it would not be too complicated to add this feature. Feel free to suggest a PR ;
- You can remove the "Add" button using the [`limit(1)` method](https://whitecube.github.io/nova-flexible-content/#/?id=limiting-layouts) ;
- You can store the field's value as a JSON object using a [custom Resolver](https://whitecube.github.io/nova-flexible-content/#/?id=custom-resolver-classes).

I'm closing this issue since there are alternative solutions available and it is not directly connected with the purpose of this package.

Have a great day!

**Comment by tpetry** [comment]
I do understand your stance on the topic. But sadly all the other solutions can't be fixed because their starting concept is already doomed (e.g. need to replicate every nova field). But you're also right in that most of what i want to achieve (any many other want to achieve by `64robots/nova-fields` can be done with your package with custom logic.

Could you reopen the issue so i or someone else is aware your package could be easily extended to fullfill the need? If i understand correctly only up/down/delete buttons feature would need to be added. So this issue could exist solely for this feature.

**Comment by Nyratas** [comment]
I would suggest a dedicated section & example in the package's [full docs](https://whitecube.github.io/nova-flexible-content/#/) instead of leaving the issue "open", which gives a wrong impression on the amount of real open issues.

@voidgraphics what do you think? We could have a chapter at the end called "Use cases" or "Extended use cases" or something like that. I have a few examples in mind and this one could be part of it.

**Comment by tpetry** [comment]
But it cant (yet) be an example in the documentation because its not possible yet.

**Comment by voidgraphics** [comment]
@Nyratas Yes, I think having more examples in the full docs would be great. If they get complex, maybe they would benefit from being on their own page/code sandbox or something.

@tpetry I opened a new issue for the feature request (#101). Since we do not see an immediate need for this feature, I doubt we will tackle it ourselves, so feel free to submit a PR for it yourself or encourage others to tackle it. I'm pretty sure it's a fairly easy feature to add.

**Comment by Nyratas** [comment]
@tpetry Except for point 1, which is just an UI enhancement (the delete up/down buttons won't prevent the "hack" from working since there's only on layout possible thanks to the `$field->limit(1)` call), it is possible implement your request. You should create a custom resolver for the field's storage, that's all.

```php
Flexible::make('My JSON field', 'json')
    ->addLayout('JSON object', 'json', [
        // ... your fields
    ])
    ->limit(1)
    ->resolver(\App\Nova\Flexible\Resolvers\MyJsonResolver::class);
```

```php
namespace App\Nova\Flexible\Resolvers;

use Whitecube\NovaFlexibleContent\Value\ResolverInterface;

class MyJsonResolver implements ResolverInterface
{
    /**
     * get the field's value
     *
     * @param  mixed  $resource
     * @param  string $attribute
     * @param  Whitecube\NovaFlexibleContent\Layouts\Collection $layouts
     * @return Illuminate\Support\Collection
     */
    public function get($resource, $attribute, $layouts)
    {
        // Transform the attribute into a collection, even if it is just a single JSON object
    }

    /**
     * Set the field's value
     *
     * @param  mixed  $model
     * @param  string $attribute
     * @param  Illuminate\Support\Collection $groups
     * @return string
     */
    public function set($model, $attribute, $groups)
    {
        // Extract the first element of the groups and save it as a single JSON object
    }
}
```
